enum EMPLOYEE {
  NOT_FOUND = 'EMPLOYEE_NOT_FOUND',
  EMAIL_ALREADY_EXIST = 'USER_EMAIL_ALREADY_EXIST',
  PHONE_ALREADY_EXIST = 'USER_PHONE_ALREADY_EXIST',
  INCORRECT_EMAIL_OR_PASSWORD = 'USER_INCORRECT_EMAIL_OR_PASSWORD',
  UNAUTHORIZED = 'USER_UNAUTHORIZED',
  INVALID_NAME = "INVALID_NAME",
  INVALID_EMAIL = "INVALID_EMAIL",
  INVALID_PHONE = "INVALID_PHONE",
  WEAK_PASSWORD = "WEAK_PASSWORD",
}

enum MANAGER {
    NOT_FOUND = 'MANAGER_NOT_FOUND',
    PERMISSION_DENIED = 'MANAGER_PERMISSION_DENIED',

}
enum LEAD {
    NOT_FOUND = 'LEAD_NOT_FOUND'
}
enum COMPANY {
    NOT_FOUND = 'COMPANY_NOT_FOUND',
    INVALID_COMPANY_NAME = 'INVALID_COMPANY_NAME'
}
enum ORGANIZATION {
    NOT_FOUND = 'NOT_FOUND',
    PLATFORM_NOT_FOUND = 'PLATFORM_NOT_FOUND',
    INVALID_ORGANIZATION_PLATFORM_DETAILS = 'INVALID_ORGANIZATION_PLATFORM_DETAILS',
    INVALID_NAME = 'INVALID_NAME'

}
enum REVIEW {
    INVALID_REVIEW_PLATFORM_DETAILS = 'INVALID_REVIEW_PLATFORM_DETAILS'
}
enum PROFILE {
  INVALID_FIRSTNAME = 'INVALID_FIRSTNAME',
  INVALID_SURNAME = 'INVALID_SURNAME'
}
enum SUBSCRIPTION {
    INVALID_PERIOD = 'SUBSCRIPTION_INVALID_PERIOD',
    INVALID_PRICE = 'SUBSCRIPTION_INVALID_PRICE'
}
enum TARIFF {
    NOT_FOUND = 'TARIFF_NOT_FOUND'
}
enum COMMON {
    UNAUTHORIZED = "UNAUTHORIZED",
    INVALID_NAME = "INVALID_NAME",
    INVALID_EMAIL = "INVALID_EMAIL",
    INVALID_PHONE = "INVALID_PHONE",
}

enum PLACEMENT {
    TWOGIS_NOT_FOUND = 'PLACEMENT_TWOGIS_NOT_FOUND'
}
export const EXCEPTION = {
    COMMON: COMMON,
    MANAGER: MANAGER,
    EMPLOYEE: EMPLOYEE,
    ORGANIZATION: ORGANIZATION,
    REVIEW: REVIEW,
    COMPANY: COMPANY,
    SUBSCRIPTION: SUBSCRIPTION,
    TARIFF: TARIFF,
    PROFILE: PROFILE,
    LEAD: LEAD,
    PLACEMENT: PLACEMENT,
}
