enum EMPLOYEE {
  NOT_FOUND = 'EMPLOYEE_NOT_FOUND',
  EMAIL_ALREADY_EXIST = 'USER_EMAIL_ALREADY_EXIST',
  PHONE_ALREADY_EXIST = 'USER_PHONE_ALREADY_EXIST',
  INCORRECT_EMAIL_OR_PASSWORD = 'USER_INCORRECT_EMAIL_OR_PASSWORD',
  UNAUTHORIZED = 'USER_UNAUTHORIZED',
  INVALID_NAME = "INVALID_NAME",
  INVALID_EMAIL = "INVALID_EMAIL",
  INVALID_PHONE = "INVALID_PHONE",
  WEAK_PASSWORD = "WEAK_PASSWORD",
}

enum MANAGER {
    NOT_FOUND = 'MANAGER_NOT_FOUND',
    PERMISSION_DENIED = 'MANAGER_PERMISSION_DENIED',

}
enum COMPANY {
    NOT_FOUND = 'NOT_FOUND',
    INVALID_COMPANY_NAME = 'INVALID_COMPANY_NAME'
}
enum TARIFF {
  ALREADY_ACTIVE = 'ALREADY_ACTIVE',
  ALREADY_INACTIVE = 'ALREADY_INACTIVE'
}
enum ORGANIZATION {
    NOT_FOUND = 'NOT_FOUND',
    PLATFORM_NOT_FOUND = 'PLATFORM_NOT_FOUND',
    INVALID_ORGANIZATION_PLATFORM_DETAILS = 'INVALID_ORGANIZATION_PLATFORM_DETAILS',
    INVALID_NAME = 'INVALID_NAME'

}
enum REVIEW {
    INVALID_REVIEW_PLATFORM_DETAILS = 'INVALID_REVIEW_PLATFORM_DETAILS'
}
enum PROFILE {
  INVALID_FIRSTNAME = 'INVALID_FIRSTNAME',
  INVALID_SURNAME = 'INVALID_SURNAME'
}
enum TARIFF {
    INVALID_PRICE= 'INVALID_PRICE'
}

export const EXCEPTION = {
    MANAGER: MANAGER,
    EMPLOYEE: EMPLOYEE,
    ORGANIZATION: ORGANIZATION,
    REVIEW: REVIEW,
    COMPANY: COMPANY,
    TARIFF: TARIFF,
    PROFILE: PROFILE
}
