const PARTNER = {
  SUCCESS_REGISTER: 'SUCCESS_PARTNER_REGISTER',
  SUCCESS_GET_LIST: 'SUCCESS_GET_PARTNER_LIST',
  SUCCESS_MANAGER_REVIEW: 'SUCCESS_MANAGER_REVIEW',
};

const USER = {
  SUCCESS_LOGIN: 'SUCCESS_USER_LOGIN',
  SUCCESS_RECOVERY_BY_EMAIL: 'SUCCESS_RECOVERY_BY_EMAIL',
  SUCCESS_MULTIPLE_LOGIN: 'SUCCESS_MULTIPLE_LOGIN',
  SUCCESS_CHANGE_PASSWORD: `SUCCESS_PASSWORD_CHANGED`,
};

const ORGANIZATION = {
  SUCCESS_CREATE: 'SUCCESS_ORGANIZATION_CREATE',
  SUCCESS_ORGANIZATIONS_LIST: `SUCCESS_ORGANIZATIONS_LIST`,
  SUCCESS_PHOTO_UPLOADING: `SUCCESS_PHOTO_UPLOADING`,
  SUCCESS_ORGANIZATION_GROUP_ADDED: `SUCCESS_ORGANIZATION_GROUP_ADDED`,
  SUCCESS_ORGANIZATION_GROUP_CHANGED: `SUCCESS_ORGANIZATION_GROUP_CHANGED`,
  SUCCESS_DETAILED_LIST: `SUCCESS_DETAILED_ORGANIZATION_LIST`,
  SUCCESS_ADD_CREDENTIALS: `SUCCESS_ADD_CREDENTIALS`,
  SUCCESS_UPDATE_AUTO_REPLY: `SUCCESS_UPDATE_AUTO_REPLY`,
  SUCCESS_UPDATE: `SUCCESS_UPDATE`,
  SUCCESS_UPDATE_AUTO_REPLY_PATTERN: `SUCCESS_UPDATE_AUTO_REPLY_PATTERN`,
  SUCCESS_GPT_ORDER: 'SUCCESS_GPT_ORDER',
};

const YANDEX_ORGANIZATION = {
  SUCCESS_CREATE: 'SUCCESS_ORGANIZATION_CREATE_YANDEX',
  SUCCESS_ORGANIZATIONS_LIST: `SUCCESS_ORGANIZATIONS_LIST_YANDEX`,
  SUCCESS_PHOTO_UPLOADING: `SUCCESS_PHOTO_UPLOADING_YANDEX`,
  SUCCESS_ORGANIZATION_GROUP_ADDED: `SUCCESS_ORGANIZATION_GROUP_ADDED_YANDEX`,
  SUCCESS_ORGANIZATION_GROUP_CHANGED: `SUCCESS_ORGANIZATION_GROUP_CHANGED_YANDEX`,
  SUCCESS_DETAILED_LIST: `SUCCESS_DETAILED_ORGANIZATION_LIST_YANDEX`,
  SUCCESS_ADD_CREDENTIALS: `SUCCESS_ADD_CREDENTIALS_YANDEX`,
  SUCCESS_UPDATE_AUTO_REPLY: `SUCCESS_UPDATE_AUTO_REPLY_YANDEX`,
  SUCCESS_UPDATE: `SUCCESS_UPDATE_YANDEX`,
  SUCCESS_UPDATE_AUTO_REPLY_PATTERN: `SUCCESS_UPDATE_AUTO_REPLY_PATTERN_YANDEX`,
  SUCCESS_GPT_ORDER: 'SUCCESS_GPT_ORDER_YANDEX',
};

const PROFILE = {
  SUCCESS_ADD_BOT: 'SUCCESS_BOT_ADDED',
  SUCCESS_GET_LIST: 'SUCCESS_GET_LIST',
  SUCCESS_CHANGE_AVATAR: 'SUCCESS_CHANGE_AVATAR',
};

const YANDEX_PROFILE = {
  SUCCESS_ADD_BOT: 'SUCCESS_BOT_ADDED_YANDEX',
  SUCCESS_GET_LIST: 'SUCCESS_GET_LIST_YANDEX',
  SUCCESS_CHANGE_AVATAR: 'SUCCESS_CHANGE_AVATAR_YANDEX',
};

const REVIEW = {
  SUCCESS_REVIEW_CREATION: 'SUCCESS_REVIEW_CREATED_SUCCESSFULLY',
  SUCCESS_GET_LIST: 'SUCCESS_GET_REVIEW_LIST',
  SUCCESS_GENERATED_LIST: 'SUCCESS_GET_GENERATED_REVIEW_LIST',
  SUCCESS_APPROVE: 'SUCCESS_REVIEW_APPROVE',
  SUCCESS_REJECT: 'SUCCESS_REVIEW_REJECT',
  SUCCESS_EDIT: 'SUCCESS_REVIEW_EDIT',
  SUCCESS_DELETE: 'SUCCESS_REVIEW_DELETE',
};

const YANDEX_REVIEW = {
  SUCCESS_REVIEW_CREATION: 'SUCCESS_REVIEW_CREATED_SUCCESSFULLY_YANDEX',
  SUCCESS_GET_LIST: 'SUCCESS_GET_REVIEW_LIST_YANDEX',
  SUCCESS_GENERATED_LIST: 'SUCCESS_GET_GENERATED_REVIEW_LIST_YANDEX',
  SUCCESS_APPROVE: 'SUCCESS_REVIEW_APPROVE_YANDEX',
  SUCCESS_REJECT: 'SUCCESS_REVIEW_REJECT_YANDEX',
  SUCCESS_EDIT: 'SUCCESS_REVIEW_EDIT_YANDEX',
  SUCCESS_DELETE: 'SUCCESS_REVIEW_DELETE_YANDEX',
};

const MEDIA = {
  CREATE_REVIEW: 'SUCCESS_MEDIA_CREATE_REVIEW',
  CREATE_MANAGER_REVIEW: 'SUCCESS_MANAGER_REVIEW',
};

const NOTIFICATION = {
  SUCCESS_CREATE: 'SUCCESS_NOTIFICATION_CREATE',
  SUCCESS_EDIT: 'SUCCESS_NOTIFICATION_EDIT',
  SUCCESS_DELETE: 'SUCCESS_NOTIFICATION_DELETE',
};

const SHOP_REVIEWER = {
  SUCCESS_ACTIVATE: 'SUCCESS_SHOP_REVIEW_ACTIVATE',
};

const FINANCE = {
  REFILL_PARTNER_BALANCE: 'SUCCESS_REFILL_PARTNER_BALANCE',
};

const METRIC = {
  REVIEW_METRIC_LIST: 'SUCCESS_REVIEW_METRIC_LIST',
};

const COMPLAINT = {
  CLARIFICATION_REPLY_SENT: 'SUCCESS_CLARIFICATION_REPLY_SENT',
  REVIEW_SET_COMPLAINT_TEMPLATE: 'SUCCESS_REVIEW_SET_COMPLAINT_TEMPLATE',
  COMPLAINT_MARKED_AS_READ: 'SUCCESS_COMPLAINT_MARKED_AS_READ',
}

export const SUCCESS = {
  PARTNER,
  USER,
  ORGANIZATION,
  YANDEX_ORGANIZATION,
  PROFILE,
  YANDEX_PROFILE,
  REVIEW,
  YANDEX_REVIEW,
  MEDIA,
  SHOP_REVIEWER,
  FINANCE,
  NOTIFICATION,
  METRIC,
  COMPLAINT,
};
