export const QUEUES = {
  SYNC_ORGANIZATION_REVIEWS_QUEUE: 'SYNC_ORGANIZATION_REVIEWS_QUEUE',
  SYNC_YANDEX_ORGANIZATION_REVIEWS_QUEUE: 'SYNC_YANDEX_ORGANIZATION_REVIEWS_QUEUE',
  SEND_REVIEW_QUEUE: 'SEND_REVIEW_QUEUE',
  SEND_YANDEX_REVIEW_QUEUE: 'SEND_YANDEX_REVIEW_QUEUE',
  GPT_GENERATE_REVIEWS_QUEUE: 'GPT_GENERATE_REVIEWS_QUEUE',
  SEND_REPLY_QUEUE: 'SEND_REPLY_QUEUE',
  SEND_MAIL_QUEUE: 'SEND_MAIL_QUEUE',
  SEND_AMO_CRM_QUEUE: 'SEND_AMO_CRM_QUEUE',
  CREATE_SNAPSHOT_QUEUE: 'CREATE_SNAPSHOT_QUEUE',
  WHATSAPP_INSTANCE_ID_QUEUE: 'WHATSAPP_INSTANCE_ID_QUEUE',
  SEND_COMPLAINT_CLARIFICATION_QUEUE: 'SEND_CLARIFICATION_QUEUE',
  SEND_COMPLAINT_FORMAL_QUEUE: 'SEND_COMPLAINT_FORMAL_QUEUE',
  SYNC_ORGANIZATION_RATINGS_QUEUE: 'SYNC_ORGANIZATION_RATINGS_QUEUE',
};

export enum QUEUE_TYPE {
  DELAY = 'delay',
  REPEAT = 'repeat',
}

export const queueInjectionList = () => {
  const array: { name: string }[] = [];
  for (const key in QUEUES) {
    const value = QUEUES[key];
    array.push({ name: value });
  }
  return array;
};

type QueueKeysType = keyof typeof QUEUES;
export type QueueValueType = (typeof QUEUES)[QueueKeysType];
