import { MigrationInterface, QueryRunner } from "typeorm";

export class Init1756885363855 implements MigrationInterface {
    name = 'Init1756885363855'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE "tariff_features" ("tariff_id" uuid NOT NULL, "company_data_sync" boolean NOT NULL, "multi_access" boolean NOT NULL, "register_placement" boolean NOT NULL, "review_reply" boolean NOT NULL, "review_auto_reply" boolean NOT NULL, "review_complaint" boolean NOT NULL, "review_auto_complaint" boolean NOT NULL, "analysis_review" boolean NOT NULL, "analysis_by_radius" boolean NOT NULL, "analysis_competitor" boolean NOT NULL, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, CONSTRAINT "PK_43cd50b8f14c23c364739a6cbbc" PRIMARY KEY ("tariff_id"))`);
        await queryRunner.query(`CREATE TABLE "tariff" ("id" uuid NOT NULL, "is_active" boolean NOT NULL, "price" integer, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, CONSTRAINT "PK_bbeac9df199ea1c22c6dea75c2f" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "subscription" ("id" uuid NOT NULL, "company_id" uuid NOT NULL, "tariff_id" uuid NOT NULL, "is_expire" boolean NOT NULL, "price" character varying NOT NULL, "start" TIMESTAMP WITH TIME ZONE NOT NULL, "end" TIMESTAMP WITH TIME ZONE NOT NULL, "frozen_at" TIMESTAMP WITH TIME ZONE, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, CONSTRAINT "PK_8c3e00ebd02103caa1174cd5d9d" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "twogis_profile_placement_detail" ("profile_id" uuid NOT NULL, "external_id" character varying NOT NULL, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, CONSTRAINT "UQ_93d2aaf19c1a062aad4702cdeb6" UNIQUE ("external_id"), CONSTRAINT "PK_0f6f38aa252ea3dbffed2b020a4" PRIMARY KEY ("profile_id"))`);
        await queryRunner.query(`CREATE TABLE "yandex_profile_placement_detail" ("profile_id" uuid NOT NULL, "external_id" character varying NOT NULL, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, CONSTRAINT "UQ_68f8a951bc8e1824e9b99917b74" UNIQUE ("external_id"), CONSTRAINT "PK_7576bc0c60ddb798ec4c04c921e" PRIMARY KEY ("profile_id"))`);
        await queryRunner.query(`CREATE TYPE "public"."profile_platform_enum" AS ENUM('TWOGIS', 'YANDEX', 'GOOGLE')`);
        await queryRunner.query(`CREATE TABLE "profile" ("id" uuid NOT NULL, "firstname" character varying, "last_name" character varying, "avatar" text, "platform" "public"."profile_platform_enum" NOT NULL, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, CONSTRAINT "PK_3dd8bfc97e4a77c70971591bdcb" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "twogis_review_placement_detail" ("review_id" uuid NOT NULL, "external_id" character varying NOT NULL, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, CONSTRAINT "UQ_b38d12ceb81b30c813d45caabad" UNIQUE ("external_id"), CONSTRAINT "PK_735f8e8206bbe742e8fd4acea7a" PRIMARY KEY ("review_id"))`);
        await queryRunner.query(`CREATE TABLE "yandex_review_placement_detail" ("review_id" uuid NOT NULL, "external_id" character varying NOT NULL, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, CONSTRAINT "UQ_a1a1a8cffbd2c23b89ab3ecebc3" UNIQUE ("external_id"), CONSTRAINT "PK_de7cf6c025686d7e67fe09ac7e0" PRIMARY KEY ("review_id"))`);
        await queryRunner.query(`CREATE TABLE "review_media" ("id" uuid NOT NULL, "review_id" uuid NOT NULL, "url" character varying NOT NULL, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, CONSTRAINT "PK_48fc569cdffffb4d92e80392203" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "review_reply" ("id" uuid NOT NULL, "external_id" character varying NOT NULL, "text" character varying NOT NULL, "is_official" boolean NOT NULL, "profile_id" uuid NOT NULL, "review_id" uuid NOT NULL, "type" character varying NOT NULL, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, CONSTRAINT "PK_caae9fee63836edffb507b65606" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."review_platform_enum" AS ENUM('TWOGIS', 'YANDEX', 'GOOGLE')`);
        await queryRunner.query(`CREATE TABLE "review" ("id" uuid NOT NULL, "text" text NOT NULL, "rating" integer NOT NULL, "profile_id" uuid NOT NULL, "placement_id" uuid NOT NULL, "platform" "public"."review_platform_enum" NOT NULL, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, CONSTRAINT "PK_2e4299a343a81574217255c00ca" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "yandex_placement_detail" ("placement_id" uuid NOT NULL, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, CONSTRAINT "PK_d26b4342d210cff27aee8eac38c" PRIMARY KEY ("placement_id"))`);
        await queryRunner.query(`CREATE TABLE "twogis_placement_detail" ("placement_id" uuid NOT NULL, "cabinet_login" character varying, "cabinet_password" character varying, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, CONSTRAINT "PK_249be0325372b2c87ade0c06bac" PRIMARY KEY ("placement_id"))`);
        await queryRunner.query(`CREATE TABLE "auto_reply" ("id" uuid NOT NULL, "is_enabled" boolean NOT NULL, "placement_id" uuid NOT NULL, "start_time" TIME, "end_time" TIME, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, CONSTRAINT "REL_73ac0cd39a9c4b25c088f4d9c0" UNIQUE ("placement_id"), CONSTRAINT "PK_6d856699da1e90de4b796faedc6" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."organization_placement_platform_enum" AS ENUM('TWOGIS', 'YANDEX', 'GOOGLE')`);
        await queryRunner.query(`CREATE TABLE "organization_placement" ("id" uuid NOT NULL, "external_id" character varying NOT NULL, "organization_id" uuid NOT NULL, "platform" "public"."organization_placement_platform_enum" NOT NULL, "rating" numeric(3,1) NOT NULL DEFAULT '0', "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, CONSTRAINT "UQ_eee42ddef7bf6cc9f7ddde548d6" UNIQUE ("external_id"), CONSTRAINT "PK_9664647b5094f03bb5a44799516" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."working_schedule_entries_day_of_week_enum" AS ENUM('MONDAY', 'TUESDAY', 'WEDNESDAY', 'THURSDAY', 'FRIDAY', 'SATURDAY', 'SUNDAY')`);
        await queryRunner.query(`CREATE TABLE "working_schedule_entries" ("unique_relation" character varying NOT NULL, "schedule_id" uuid NOT NULL, "day_of_week" "public"."working_schedule_entries_day_of_week_enum" NOT NULL, "start_time" TIME, "end_time" TIME, "break_start_time" TIME, "break_end_time" TIME, CONSTRAINT "UQ_fb37850f405ec52d0df3bbd0a09" UNIQUE ("schedule_id", "day_of_week"), CONSTRAINT "PK_c464e6cee79e3bfd0b85b04fd59" PRIMARY KEY ("unique_relation"))`);
        await queryRunner.query(`CREATE TABLE "organization_working_schedules" ("id" uuid NOT NULL, "organization_id" uuid NOT NULL, "is_temporary_closed" boolean NOT NULL DEFAULT false, CONSTRAINT "REL_afe6b57f827e34bb0645bb34ce" UNIQUE ("organization_id"), CONSTRAINT "PK_45f3e2d3608a79f3991a743d176" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."contact_points_type_enum" AS ENUM('WHATSAPP', 'VIBER', 'INSTAGRAM', 'EMAIL', 'PHONE', 'TELEGRAM', 'WEBSITE')`);
        await queryRunner.query(`CREATE TABLE "contact_points" ("id" uuid NOT NULL, "organization_id" uuid NOT NULL, "type" "public"."contact_points_type_enum" NOT NULL, "value" character varying(255) NOT NULL, CONSTRAINT "PK_4bc7017b4c818a96c7962fb9647" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "organization_group" ("id" uuid NOT NULL, "organization_id" character varying NOT NULL, "name" character varying NOT NULL, CONSTRAINT "PK_999bf5dafba09258280309fc0e7" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "organization_address" ("organization_id" uuid NOT NULL, "country" character varying NOT NULL, "city" character varying NOT NULL, "district" character varying NOT NULL, "street" character varying NOT NULL, "housenumber" character varying NOT NULL, "latitude" numeric(10,7) NOT NULL, "longitude" numeric(10,7) NOT NULL, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, CONSTRAINT "PK_9593f84307839721a61831d1c65" PRIMARY KEY ("organization_id"))`);
        await queryRunner.query(`CREATE TABLE "external_rubric" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "external_id" character varying NOT NULL, "rubric_id" uuid NOT NULL, "name" character varying NOT NULL, "platform" character varying NOT NULL, CONSTRAINT "UQ_963aced1bbdf737b4401894f83d" UNIQUE ("platform", "external_id"), CONSTRAINT "PK_c18fa30e32a13cfb44c96979dfb" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "rubric" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying NOT NULL, CONSTRAINT "PK_c6926c4b9f70196fae0f95c5691" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "organization" ("id" uuid NOT NULL, "name" character varying NOT NULL, "company_id" uuid NOT NULL, "is_active" boolean NOT NULL, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, "group_id" uuid, CONSTRAINT "PK_472c1f99a32def1b0abb219cd67" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "company" ("id" uuid NOT NULL, "name" character varying NOT NULL, "manager_id" uuid NOT NULL, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, CONSTRAINT "PK_056f7854a7afdba7cbd6d45fc20" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "user_permission" ("id" uuid NOT NULL, "role_id" uuid NOT NULL, "module" character varying NOT NULL, "permission" character varying NOT NULL, "organization_id" character varying, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, CONSTRAINT "PK_a7326749e773c740a7104634a77" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "user_role" ("id" uuid NOT NULL, "name" character varying NOT NULL, "type" character varying NOT NULL, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, CONSTRAINT "PK_fb2e442d14add3cefbdf33c4561" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "user" ("id" uuid NOT NULL, "name" character varying NOT NULL, "email" character varying NOT NULL, "phone" character varying NOT NULL, "password" character varying, "avatar" text, "company_id" uuid, "role_id" uuid NOT NULL, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, CONSTRAINT "UQ_e12875dfb3b1d92d7d7c5377e22" UNIQUE ("email"), CONSTRAINT "UQ_8e1f623798118e629b46a9e6299" UNIQUE ("phone"), CONSTRAINT "PK_cace4a159ff9f2512dd42373760" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "proxy" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "ip" character varying NOT NULL, "port" integer NOT NULL, "login" character varying NOT NULL, "password" character varying NOT NULL, "is_blocked" boolean NOT NULL DEFAULT false, "company_id" uuid, CONSTRAINT "UQ_4ef986f05383175b971e50d2d84" UNIQUE ("ip"), CONSTRAINT "PK_581edf779fc90b8d2687c658276" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "placement_moder_confirmation" ("id" uuid NOT NULL, "name" boolean NOT NULL, "address" boolean NOT NULL, "reference_point" boolean NOT NULL, "entrance" boolean NOT NULL, CONSTRAINT "PK_d43af9bcb549c24abe23bbc4b0d" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "mail" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "template" character varying NOT NULL, "user_id" uuid NOT NULL, "email" character varying NOT NULL, "payload" json NOT NULL, "send_date" TIMESTAMP WITH TIME ZONE, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, CONSTRAINT "PK_5407da42b983ba54c6c62d462d3" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "lead-contact" ("lead_id" uuid NOT NULL, "company_name" character varying NOT NULL, "phone" character varying NOT NULL, "name" character varying NOT NULL, "email" character varying NOT NULL, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, CONSTRAINT "PK_191fa48449f4c3f3eca60f07345" PRIMARY KEY ("lead_id"))`);
        await queryRunner.query(`CREATE TABLE "lead" ("id" uuid NOT NULL, "manager_id" uuid, "processed_at" TIMESTAMP WITH TIME ZONE, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, CONSTRAINT "PK_ca96c1888f7dcfccab72b72fffa" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "auto_reply_template" ("id" uuid NOT NULL, "text" character varying NOT NULL, "placement_id" uuid NOT NULL, "language" character varying NOT NULL, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, CONSTRAINT "PK_42584436db4b01a83698b986b16" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "review_complaint" ("id" uuid NOT NULL, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, CONSTRAINT "PK_1116c61b835b3b38ed8b6a7ae5f" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "rubric_external_rubric" ("rubric_id" uuid NOT NULL, "external_rubric_id" uuid NOT NULL, CONSTRAINT "PK_55fcffa106648a74feea8c21905" PRIMARY KEY ("rubric_id", "external_rubric_id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_39a0921a9775c3fe56e7e13092" ON "rubric_external_rubric" ("rubric_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_70d70e1ef5b3a2fd7f475a78c7" ON "rubric_external_rubric" ("external_rubric_id") `);
        await queryRunner.query(`CREATE TABLE "organization_rubric" ("rubric_id" uuid NOT NULL, "organization_id" uuid NOT NULL, CONSTRAINT "PK_75eee9b8959737a40883eeb1eb8" PRIMARY KEY ("rubric_id", "organization_id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_042339bd12fbb91b8f51518480" ON "organization_rubric" ("rubric_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_0a5633a53f24177a7e453d1ba3" ON "organization_rubric" ("organization_id") `);
        await queryRunner.query(`ALTER TABLE "tariff_features" ADD CONSTRAINT "FK_43cd50b8f14c23c364739a6cbbc" FOREIGN KEY ("tariff_id") REFERENCES "tariff"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "subscription" ADD CONSTRAINT "FK_27020e672df258486027d684a2c" FOREIGN KEY ("tariff_id") REFERENCES "tariff"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "subscription" ADD CONSTRAINT "FK_040d4d92b5bf63a5406f9be65e2" FOREIGN KEY ("company_id") REFERENCES "company"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "twogis_profile_placement_detail" ADD CONSTRAINT "FK_0f6f38aa252ea3dbffed2b020a4" FOREIGN KEY ("profile_id") REFERENCES "profile"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "yandex_profile_placement_detail" ADD CONSTRAINT "FK_7576bc0c60ddb798ec4c04c921e" FOREIGN KEY ("profile_id") REFERENCES "profile"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "twogis_review_placement_detail" ADD CONSTRAINT "FK_735f8e8206bbe742e8fd4acea7a" FOREIGN KEY ("review_id") REFERENCES "review"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "yandex_review_placement_detail" ADD CONSTRAINT "FK_de7cf6c025686d7e67fe09ac7e0" FOREIGN KEY ("review_id") REFERENCES "review"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "review_media" ADD CONSTRAINT "FK_f7cd6d7c745b96f951d1e43d9a4" FOREIGN KEY ("review_id") REFERENCES "review"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "review_reply" ADD CONSTRAINT "FK_0fc13d32bb48a7d6b5f437660f1" FOREIGN KEY ("profile_id") REFERENCES "profile"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "review_reply" ADD CONSTRAINT "FK_82cdeb2572bf8482a253079db49" FOREIGN KEY ("review_id") REFERENCES "review"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "review" ADD CONSTRAINT "FK_f8d679b3d1177515113e24f5b10" FOREIGN KEY ("profile_id") REFERENCES "profile"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "review" ADD CONSTRAINT "FK_abb71ed48f4df2e6bf7f7ff9ab3" FOREIGN KEY ("placement_id") REFERENCES "organization_placement"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "yandex_placement_detail" ADD CONSTRAINT "FK_d26b4342d210cff27aee8eac38c" FOREIGN KEY ("placement_id") REFERENCES "organization_placement"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "twogis_placement_detail" ADD CONSTRAINT "FK_249be0325372b2c87ade0c06bac" FOREIGN KEY ("placement_id") REFERENCES "organization_placement"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "auto_reply" ADD CONSTRAINT "FK_73ac0cd39a9c4b25c088f4d9c06" FOREIGN KEY ("placement_id") REFERENCES "organization_placement"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "organization_placement" ADD CONSTRAINT "FK_03111de85a4d836e57d78f5c7e4" FOREIGN KEY ("organization_id") REFERENCES "organization"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "working_schedule_entries" ADD CONSTRAINT "FK_69d8e54c2bec82d832ab17a50c4" FOREIGN KEY ("schedule_id") REFERENCES "organization_working_schedules"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "organization_working_schedules" ADD CONSTRAINT "FK_afe6b57f827e34bb0645bb34ced" FOREIGN KEY ("organization_id") REFERENCES "organization"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "contact_points" ADD CONSTRAINT "FK_6224ea39c99e8590c338c126611" FOREIGN KEY ("organization_id") REFERENCES "organization"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "organization_address" ADD CONSTRAINT "FK_9593f84307839721a61831d1c65" FOREIGN KEY ("organization_id") REFERENCES "organization"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "organization" ADD CONSTRAINT "FK_9da706d83455a070ce3be81eb30" FOREIGN KEY ("company_id") REFERENCES "company"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "organization" ADD CONSTRAINT "FK_999bf5dafba09258280309fc0e7" FOREIGN KEY ("group_id") REFERENCES "organization_group"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_permission" ADD CONSTRAINT "FK_b46a24ea468033187b20a1e65cf" FOREIGN KEY ("role_id") REFERENCES "user_role"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user" ADD CONSTRAINT "FK_9e70b5f9d7095018e86970c7874" FOREIGN KEY ("company_id") REFERENCES "company"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user" ADD CONSTRAINT "FK_fb2e442d14add3cefbdf33c4561" FOREIGN KEY ("role_id") REFERENCES "user_role"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "mail" ADD CONSTRAINT "FK_c22035b7ce4b93e89422b216da4" FOREIGN KEY ("user_id") REFERENCES "user"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "lead-contact" ADD CONSTRAINT "FK_191fa48449f4c3f3eca60f07345" FOREIGN KEY ("lead_id") REFERENCES "lead"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "rubric_external_rubric" ADD CONSTRAINT "FK_39a0921a9775c3fe56e7e130924" FOREIGN KEY ("rubric_id") REFERENCES "rubric"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "rubric_external_rubric" ADD CONSTRAINT "FK_70d70e1ef5b3a2fd7f475a78c7f" FOREIGN KEY ("external_rubric_id") REFERENCES "external_rubric"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "organization_rubric" ADD CONSTRAINT "FK_042339bd12fbb91b8f515184804" FOREIGN KEY ("rubric_id") REFERENCES "rubric"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "organization_rubric" ADD CONSTRAINT "FK_0a5633a53f24177a7e453d1ba3b" FOREIGN KEY ("organization_id") REFERENCES "organization"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "organization_rubric" DROP CONSTRAINT "FK_0a5633a53f24177a7e453d1ba3b"`);
        await queryRunner.query(`ALTER TABLE "organization_rubric" DROP CONSTRAINT "FK_042339bd12fbb91b8f515184804"`);
        await queryRunner.query(`ALTER TABLE "rubric_external_rubric" DROP CONSTRAINT "FK_70d70e1ef5b3a2fd7f475a78c7f"`);
        await queryRunner.query(`ALTER TABLE "rubric_external_rubric" DROP CONSTRAINT "FK_39a0921a9775c3fe56e7e130924"`);
        await queryRunner.query(`ALTER TABLE "lead-contact" DROP CONSTRAINT "FK_191fa48449f4c3f3eca60f07345"`);
        await queryRunner.query(`ALTER TABLE "mail" DROP CONSTRAINT "FK_c22035b7ce4b93e89422b216da4"`);
        await queryRunner.query(`ALTER TABLE "user" DROP CONSTRAINT "FK_fb2e442d14add3cefbdf33c4561"`);
        await queryRunner.query(`ALTER TABLE "user" DROP CONSTRAINT "FK_9e70b5f9d7095018e86970c7874"`);
        await queryRunner.query(`ALTER TABLE "user_permission" DROP CONSTRAINT "FK_b46a24ea468033187b20a1e65cf"`);
        await queryRunner.query(`ALTER TABLE "organization" DROP CONSTRAINT "FK_999bf5dafba09258280309fc0e7"`);
        await queryRunner.query(`ALTER TABLE "organization" DROP CONSTRAINT "FK_9da706d83455a070ce3be81eb30"`);
        await queryRunner.query(`ALTER TABLE "organization_address" DROP CONSTRAINT "FK_9593f84307839721a61831d1c65"`);
        await queryRunner.query(`ALTER TABLE "contact_points" DROP CONSTRAINT "FK_6224ea39c99e8590c338c126611"`);
        await queryRunner.query(`ALTER TABLE "organization_working_schedules" DROP CONSTRAINT "FK_afe6b57f827e34bb0645bb34ced"`);
        await queryRunner.query(`ALTER TABLE "working_schedule_entries" DROP CONSTRAINT "FK_69d8e54c2bec82d832ab17a50c4"`);
        await queryRunner.query(`ALTER TABLE "organization_placement" DROP CONSTRAINT "FK_03111de85a4d836e57d78f5c7e4"`);
        await queryRunner.query(`ALTER TABLE "auto_reply" DROP CONSTRAINT "FK_73ac0cd39a9c4b25c088f4d9c06"`);
        await queryRunner.query(`ALTER TABLE "twogis_placement_detail" DROP CONSTRAINT "FK_249be0325372b2c87ade0c06bac"`);
        await queryRunner.query(`ALTER TABLE "yandex_placement_detail" DROP CONSTRAINT "FK_d26b4342d210cff27aee8eac38c"`);
        await queryRunner.query(`ALTER TABLE "review" DROP CONSTRAINT "FK_abb71ed48f4df2e6bf7f7ff9ab3"`);
        await queryRunner.query(`ALTER TABLE "review" DROP CONSTRAINT "FK_f8d679b3d1177515113e24f5b10"`);
        await queryRunner.query(`ALTER TABLE "review_reply" DROP CONSTRAINT "FK_82cdeb2572bf8482a253079db49"`);
        await queryRunner.query(`ALTER TABLE "review_reply" DROP CONSTRAINT "FK_0fc13d32bb48a7d6b5f437660f1"`);
        await queryRunner.query(`ALTER TABLE "review_media" DROP CONSTRAINT "FK_f7cd6d7c745b96f951d1e43d9a4"`);
        await queryRunner.query(`ALTER TABLE "yandex_review_placement_detail" DROP CONSTRAINT "FK_de7cf6c025686d7e67fe09ac7e0"`);
        await queryRunner.query(`ALTER TABLE "twogis_review_placement_detail" DROP CONSTRAINT "FK_735f8e8206bbe742e8fd4acea7a"`);
        await queryRunner.query(`ALTER TABLE "yandex_profile_placement_detail" DROP CONSTRAINT "FK_7576bc0c60ddb798ec4c04c921e"`);
        await queryRunner.query(`ALTER TABLE "twogis_profile_placement_detail" DROP CONSTRAINT "FK_0f6f38aa252ea3dbffed2b020a4"`);
        await queryRunner.query(`ALTER TABLE "subscription" DROP CONSTRAINT "FK_040d4d92b5bf63a5406f9be65e2"`);
        await queryRunner.query(`ALTER TABLE "subscription" DROP CONSTRAINT "FK_27020e672df258486027d684a2c"`);
        await queryRunner.query(`ALTER TABLE "tariff_features" DROP CONSTRAINT "FK_43cd50b8f14c23c364739a6cbbc"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_0a5633a53f24177a7e453d1ba3"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_042339bd12fbb91b8f51518480"`);
        await queryRunner.query(`DROP TABLE "organization_rubric"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_70d70e1ef5b3a2fd7f475a78c7"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_39a0921a9775c3fe56e7e13092"`);
        await queryRunner.query(`DROP TABLE "rubric_external_rubric"`);
        await queryRunner.query(`DROP TABLE "review_complaint"`);
        await queryRunner.query(`DROP TABLE "auto_reply_template"`);
        await queryRunner.query(`DROP TABLE "lead"`);
        await queryRunner.query(`DROP TABLE "lead-contact"`);
        await queryRunner.query(`DROP TABLE "mail"`);
        await queryRunner.query(`DROP TABLE "placement_moder_confirmation"`);
        await queryRunner.query(`DROP TABLE "proxy"`);
        await queryRunner.query(`DROP TABLE "user"`);
        await queryRunner.query(`DROP TABLE "user_role"`);
        await queryRunner.query(`DROP TABLE "user_permission"`);
        await queryRunner.query(`DROP TABLE "company"`);
        await queryRunner.query(`DROP TABLE "organization"`);
        await queryRunner.query(`DROP TABLE "rubric"`);
        await queryRunner.query(`DROP TABLE "external_rubric"`);
        await queryRunner.query(`DROP TABLE "organization_address"`);
        await queryRunner.query(`DROP TABLE "organization_group"`);
        await queryRunner.query(`DROP TABLE "contact_points"`);
        await queryRunner.query(`DROP TYPE "public"."contact_points_type_enum"`);
        await queryRunner.query(`DROP TABLE "organization_working_schedules"`);
        await queryRunner.query(`DROP TABLE "working_schedule_entries"`);
        await queryRunner.query(`DROP TYPE "public"."working_schedule_entries_day_of_week_enum"`);
        await queryRunner.query(`DROP TABLE "organization_placement"`);
        await queryRunner.query(`DROP TYPE "public"."organization_placement_platform_enum"`);
        await queryRunner.query(`DROP TABLE "auto_reply"`);
        await queryRunner.query(`DROP TABLE "twogis_placement_detail"`);
        await queryRunner.query(`DROP TABLE "yandex_placement_detail"`);
        await queryRunner.query(`DROP TABLE "review"`);
        await queryRunner.query(`DROP TYPE "public"."review_platform_enum"`);
        await queryRunner.query(`DROP TABLE "review_reply"`);
        await queryRunner.query(`DROP TABLE "review_media"`);
        await queryRunner.query(`DROP TABLE "yandex_review_placement_detail"`);
        await queryRunner.query(`DROP TABLE "twogis_review_placement_detail"`);
        await queryRunner.query(`DROP TABLE "profile"`);
        await queryRunner.query(`DROP TYPE "public"."profile_platform_enum"`);
        await queryRunner.query(`DROP TABLE "yandex_profile_placement_detail"`);
        await queryRunner.query(`DROP TABLE "twogis_profile_placement_detail"`);
        await queryRunner.query(`DROP TABLE "subscription"`);
        await queryRunner.query(`DROP TABLE "tariff"`);
        await queryRunner.query(`DROP TABLE "tariff_features"`);
    }

}
