export enum ProxyPrefix {
  COMPANY_PROXY = 'CompanyProxy',
  USER_PROXY = 'UserProxy',
  ORGANIZATION_PROXY = 'OrganizationProxy',
  YANDEX_ORGANIZATION_PROXY = 'YandexOrganizationProxy',
  REVIEW_PROXY = 'ReviewProxy',
  LEAD_PROXY = 'LEAD_PROXY',
  SUBSCRIPTION_PROXY = 'SubscriptionProxy',
  YANDEX_REVIEW_PROXY = 'YandexReviewProxy',
  PROFILE_PROXY = 'ProfileProxy',
  YANDEX_PROFILE_PROXY = 'YandexProfileProxy',
  MAIL_PROXY = 'MailProxy',
  MEDIATOR_PROXY = 'MediatorProxy',
  FILE_PROXY = 'FileProxy',
  PLAN_PROXY = 'PlanProxy',
  YANDEX_PLAN_PROXY = 'YandexPlanProxy',
  MEDIA_PROXY = 'MediaProxy',
  LANGUAGE_PROXY = 'LanguageProxy',
  YANDEX_LANGUAGE_PROXY = 'YandexLanguageProxy',
  TARIFF_PROXY = 'TariffProxy',
  YANDEX_TARIFF_PROXY = 'YandexTariffProxy',
  MESSAGE_TEMPLATE_PROXY = 'MessageTemplateProxy',
  SHOP_PROXY = 'ShopProxy',
  SHOP_REVIEWER_PROXY = 'ShopReviewerProxy',
  WHATSAPP_PROXY = 'WhatsappProxy',
  METRIC_PROXY = 'MetricProxy',
}
